# Generated by Django 6.0.7 on 2026-07-16 00:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('manutencao', 'Em Manutenção/Indisponível')], default='disponivel', max_length=20)),
                ('quantidade_total', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('data_uso', models.DateField(default=django.utils.timezone.now)),
                ('aulas', models.CharField(choices=[('1_aula', '1ª Aula (07:00 - 07:45)'), ('2_aula', '2ª Aula (07:45 - 08:30)'), ('3_aula', '3ª Aula (08:30 - 09:15)'), ('4_aula', '4ª Aula (09:15 - 10:00)'), ('5_aula', '5ª Aula (10:15 - 11:00)'), ('6_aula', '6ª Aula (11:00 - 11:45)'), ('7_aula', '7ª Aula (11:45 - 12:30)'), ('8_aula', '8ª Aula (13:30 - 14:15)'), ('9_aula', '9ª Aula (14:15 - 15:00)'), ('10_aula', '10ª Aula (15:00 - 15:45)'), ('1_2_aula', '1ª e 2ª Aula'), ('2_3_aula', '2ª e 3ª Aula'), ('3_4_aula', '3ª e 4ª Aula'), ('4_5_aula', '4ª e 5ª Aula'), ('5_6_aula', '5ª e 6ª Aula'), ('6_7_aula', '6ª e 7ª Aula'), ('7_8_aula', '7ª e 8ª Aula'), ('8_9_aula', '8ª e 9ª Aula'), ('9_10_aula', '9ª e 10ª Aula')], default='1_aula', max_length=50)),
                ('quantidade_solicitada', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_uso', 'Em Uso'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.equipamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
