# Generated by Django 6.0.7 on 2026-07-16 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='quantidade_total',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='status',
        ),
        migrations.CreateModel(
            name='ItemEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ex: Notebook 01, Projetor A', max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20)),
                ('equipamento_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='controle.equipamento')),
            ],
        ),
    ]
